[phases.setup]
nixPkgs = ["ffmpeg", "python3", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python main_complete.py"
